kind: Deployment
apiVersion: apps/v1
metadata:
  name: micro-deploy
  labels:
    app: micro
spec:
  replicas: 4
  selector:
    matchLabels:
      app: micro
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: micro
    spec:
      containers:
      - name: micro-ctr
        image: ravishgoel/micro:1.0
        command: ["node", "."]
        ports:
        - containerPort: 3000
  